BAPSObject.prototype.Routes = {
    Login: '/baps/account/login',
    Logout: '/baps/account/logout',
    ResetPassword: '/baps/account/ResetPassword',
    ResetPasswordUpdate: '/baps/account/ResetPasswordUpdate',
    CoursePublicEventSearch: '/baps/Courses/PublicEventSearch',
    PublicEventSearch: '/baps/EventSearch/PublicEventSearch',
    DatesOtherCountries: '/baps/Courses/CourseDetails_ScheduleOtherCountries',
    RequestSpace: '/baps/GKMisc/RequestSpace',
    Register: '/baps/account/register',
    SelfRegister: '/baps/account/selfregister',
    AddToCart: '/baps/Basket/BookWithOutDelegate',
    UpdateDelegateInBasket: '/baps/Basket/UpdateDelegateInBasket',
    SearchUsers: '/baps/Contacts/SearchUsers',
    SearchUsersReports: '/baps/Contacts/SearchUsersReports',
    DeleteFromBasket: '/baps/Basket/DeleteFromBasket',
    SetPayCard: '/Baps/IConnectCheckout/SetPayCard',
    SetPayInvoice: '/Baps/IConnectCheckout/SetPayInvoice',
    SetPayPackage: '/Baps/IConnectCheckout/SetPayPackage',
    SetPaySkillsLicense: '/Baps/IConnectCheckout/SetPaySkillsLicense',
    Prepayments: '/Baps/IConnectCheckout/Prepayments',
    Packages: '/Baps/IConnectCheckout/Packages',
    SetOrderNumber: '/Baps/Basket/SetOrderNumber',
    MakeBookings: '/Baps/IConnectCheckout/MakeBookings',
    AddDelegateToCart: '/Baps/IConnectCheckout/AddDelegate',
    AddDelegateToCartRegistration: '/Baps/IConnectCheckout/AddDelegateRegistration',
    AddDelegatePayment: '/Baps/IConnectCheckout/AddDelegatePayment',
    CartTotals: '/Baps/IConnectCheckout/CartTotals',
    AddComplexPromotionCode: '/Baps/Basket/AddComplexPromotionCode',
    RemoveComplexPromotionCode: '/Baps/Basket/RemoveComplexPromotionCode',
    AddRelatedProducts: '/Baps/Basket/AddRelatedProducts',

    ListedEmailDomain: '/Baps/Account/ListedEmailDomain',

    iConnectMyCoursesELearning: '/Baps/GKiConnect/iConnectMyCoursesELearning',
    iConnectMyCoursesBookings: '/Baps/GKiConnect/iConnectMyCoursesBookings',

    iConnectPurchaseHistoryELearning: '/Baps/GKiConnect/iConnectPurchaseHistoryELearning',
    iConnectPurchaseHistoryBookings: '/Baps/GKiConnect/iConnectPurchaseHistoryBookings',
    iConnectPurchaseHistoryOrders: '/Baps/GKiConnect/iConnectPurchaseHistoryOrders',

    iConnectMyApprovalsBookings: '/Baps/GKiConnect/iConnectMyApprovalsBookings',

    iConnectDepartment: '/Baps/Organisation/Department',
    iConnectDepartmentAdd: '/Baps/Organisation/DepartmentAdd',
    iConnectDepartmentEdit: '/Baps/Organisation/DepartmentEdit',
    iConnectDepartmentPotentialMembers: '/Baps/Organisation/DepartmentPotentialMembers',
    iConnectDepartmentAddMembers: '/Baps/Organisation/DepartmentAddMembers',
    iConnectDepartmentRemoveMembers: '/Baps/Organisation/DepartmentRemoveMember',
    iConnectContactAdd: '/Baps/Account/ContactAdd',
    iConnectContactEdit: '/Baps/Account/ContactEdit',
    iConnectAccountEdit: '/Baps/Account/CurrentContactEdit',
    iConnectContactEditEmail: '/Baps/GKAccount/UpdateLogin',
    iConnectContactEditPassword: '/Baps/Account/UpdatePassword',
    //iConnectContactEditPassword: '/Baps/Account/UpdateContactPassword',

    iConnectBookingDetailNotesSave: '/Baps/BookingAmendments/BookingDetailNotesSave',
    iConnectCancelBooking: '/Baps/BookingAmendments/Cancel',
    iConnectPrepayments: '/Baps/BookingAmendments/Prepayments',
    iConnectPackages: '/Baps/BookingAmendments/Packages',
    iConnectSetPayCard: '/Baps/BookingAmendments/ChangeBookingPaymentCard',
    iConnectSetPayInvoice: '/Baps/BookingAmendments/ChangeBookingPaymentInvoice',
    iConnectSetPayPackage: '/Baps/BookingAmendments/ChangeBookingPaymentPackage',
    iConnectSetPaySkillsLicense: '/Baps/BookingAmendments/ChangeBookingPaymentPrepayment',
    iConnectNameChangeUserSearch: '/Baps/BookingAmendments/NameChangeUserSearch',
    iConnectNameChange: '/Baps/BookingAmendments/NameChange',
    iConnectNameChangeElearning: '/Baps/BookingAmendments/NameChangeELearning',
    iConnectBookingDetail: '/Baps/Bookings/BookingDetail', 
    iConnectBookingApprove: '/Baps/BookingAmendments/Approve', 

    OverviewCore: '/Baps/IConnectCheckout/OverviewCore',
    RegistrationCore: '/Baps/IConnectCheckout/RegistrationCore',
    PaymentCore: '/Baps/IConnectCheckout/PaymentCore',
    iConnectRoleRules: '/Baps/Organisation/RoleRules',
    iConnectSaveRoleRules: '/Baps/Organisation/SaveRoleRules',
    iConnectSaveRole: '/Baps/Organisation/SaveRole',    

    iConnectReportTrainingHistory: '/Baps/Reports/TrainingHistoryResults',
    iConnectReportPrePayment: '/Baps/Reports/PrePaymentsResults', 
    iConnectReportPackagesUser: '/Baps/Reports/PackagesUserResults',
    iConnectReportPackagesCustomer: '/Baps/Reports/PackagesCustomerResults',
    iConnectReportProvBookings: '/Baps/Reports/ProvisionalBookingsResults',
    iConnectReportWebUsers: '/Baps/Reports/WebUsersResults',
    iConnectReportBookingsByDate: '/Baps/Reports/BookingsByDateResults',
    iConnectReportProgressByCustomer: '/Baps/Reports/ProgressByCustomerResults',
    iConnectReportProgressByEmployee: '/Baps/Reports/ProgressByEmployeeResults',

    iConnectReportTrainingHistoryDownload: '/Baps/Reports/TrainingHistoryDownload',
    iConnectReportPrePaymentDownload: '/Baps/Reports/PrePaymentsDownload',
    iConnectReportPackagesUserDownload: '/Baps/Reports/PackagesUserDownload',
    iConnectReportPackagesCustomerDownload: '/Baps/Reports/PackagesCustomerDownload',
    iConnectReportProvBookingsDownload: '/Baps/Reports/ProvisionalBookingsDownload',
    iConnectReportWebUsersDownload: '/Baps/Reports/WebUsersDownload',
    iConnectReportBookingsByDateDownload: '/Baps/Reports/BookingsByDateDownload',
    iConnectReportProgressByCustomerDownload: '/Baps/Reports/ProgressByCustomerDownload',
    iConnectReportProgressByEmployeeDownload: '/Baps/Reports/ProgressByEmployeeDownload',

    iConnectApprovalWorkflowDepartment: '/Baps/Organisation/ApprovalWorkflowDepartment',
    iConnectDeleteApprovalLevel: '/Baps/Organisation/DeleteApprovalLevel',
    iConnectAddApprovalLevel: '/Baps/Organisation/AddApprovalLevel',
    iConnectAddApprovalAuthority: '/Baps/Organisation/AddApprovalAuthority',
    iConnectRemoveApprovalAuthority: '/Baps/Organisation/RemoveApprovalAuthority',
    iConnectAddApprovalDelegate: '/Baps/Organisation/AddApprovalDelegate',
    iConnectRemoveApprovalDelegate: '/Baps/Organisation/RemoveApprovalDelegate',
    iConnectSearchUsersForApprovalLevel: '/baps/Organisation/SearchUsersForApprovalLevel',
    iConnectApprovalDelegationList: '/Baps/Organisation/ApprovalDelegationList',

    providerLogin: '/Baps/Provider/ProviderLogin',
    providerEventListResults: '/Baps/Provider/ProviderEventListResults',
    providerEventAddEdit: '/Baps/Provider/ProviderEventAddEdit',
    providerEventCancel: '/Baps/Provider/ProviderEventCancel',
    providerCourseListResults: '/Baps/Provider/providerCourseListResults',
    providerCourseAddEdit: '/Baps/Provider/ProviderCourseEditAdd',
    ProviderBulkUploadListResults: '/Baps/Provider/ProviderBulkUploadListResults',
    ProviderBulkUpload: '/Baps/Provider/ProviderBulkUploadAdd',
    ProviderBulkUploadFileDetail: '/Baps/Provider/ProviderBulkUploadFileDetail',
    ProviderLocationListResults: '/Baps/Provider/ProviderLocationListResults',
    ProviderLocationEdit: '/Baps/Provider/ProviderLocationEdit',
    ProviderRunReport: '/Baps/Provider/RunReport',
    providerCourseDetailsJSON: '/Baps/Provider/ProviderCourseDetailsJSON',

    MenuBabyCart: '/Baps/IConnectCheckout/MenuBabyCart',
    MenuBigCart: '/Baps/IConnectCheckout/MenuBigCart',

    
    RemoveExternalTracking: '/Baps/IConnectCheckout/RemoveExternalTracking'
    
}